/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {
  // Sidebar for "Get Started"
  docsSidebar: [
    {
      type: "doc",
      id: "overview",
    },
    {
      type: "category",
      label: "Get started",
      items: [
        {
          type: "autogenerated",
          dirName: "get-started",
        },
      ],
    },
    {
      type: "category",
      label: "GPU",
      items: [
        {
          type: "autogenerated",
          dirName: "gpu",
        },
      ],
    },
    {
      type: "category",
      label: "Serverless",
      items: [
        {
          type: "autogenerated",
          dirName: "serverless",
        },
      ],
    },
    {
      type: "category",
      label: "API",
      items: [
        {
          type: "autogenerated",
          dirName: "api",
        },
      ],
    },
    {
      type: "category",
      label: "Hosting",
      items: [
        {
          type: "autogenerated",
          dirName: "hosting",
        },
      ],
    },
    {
      type: "category",
      label: "References",
      items: [
        {
          type: "autogenerated",
          dirName: "references",
        },
      ],
    },
    {
      type: "doc",
      id: "glossary",
    },
  ],

  // Sidebar for "Tutorials"
  tutorialsSidebar: [
    {
      type: "category",
      label: "Introduction",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials/introduction",
        },
      ],
    },
    {
      type: "category",
      label: "GPUs",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials/gpu",
        },
      ],
    },
    {
      type: "category",
      label: "Serverless",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials/serverless",
        },
      ],
    },
  ],
};
